/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "var(--color-primary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary": "var(--color-on-primary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "status-occupied": "var(--color-status-occupied)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface": "var(--color-surface)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "text-primary": "var(--color-text-primary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary": "var(--color-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-secondary": "var(--color-surface-secondary)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "on-background": "var(--color-on-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "status-cleaning": "var(--color-status-cleaning)",
        "outline": "var(--color-outline)",
        "on-error": "var(--color-on-error)",
        "on-tertiary": "var(--color-on-tertiary)",
        "secondary": "var(--color-secondary)",
        "tertiary": "var(--color-tertiary)",
        "error-container": "var(--color-error-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "error": "var(--color-error)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "border-subtle": "var(--color-border-subtle)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "text-secondary": "var(--color-text-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "background": "var(--color-background)",
        "bg-base": "var(--color-bg-base)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-primary": "var(--color-surface-primary)",
        "status-available": "var(--color-status-available)",
        "tertiary-container": "var(--color-tertiary-container)",
        "slate-950": "var(--color-slate-950)",
        "slate-900": "var(--color-slate-900)",
        "slate-800": "var(--color-slate-800)",
        "slate-700": "var(--color-slate-700)",
        "slate-600": "var(--color-slate-600)",
        "slate-500": "var(--color-slate-500)",
        "slate-400": "var(--color-slate-400)",
        "slate-300": "var(--color-slate-300)",
        "white": "var(--color-white)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "260px",
        "container-padding": "2rem",
        "grid-gutter": "1rem",
        "element-gap": "1.5rem"
      },
      fontFamily: {
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "room-number": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "room-number": ["48px", { "lineHeight": "1", "fontWeight": "700" }],
        "h1": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
