spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/karaoke}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:karaoke}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:karaoke}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=false
