@startuml

left to right direction
skinparam packageStyle rectangle
actor "NV Lễ tân" as Receptionist

package "Hệ thống Quản lý Karaoke" {
usecase "Quản lý trả phòng" as UC08
usecase "Tính tiền phòng" as UC_calc
usecase "Tính giờ × đơn giá" as UC_time
usecase "Tổng hợp order" as UC_order
usecase "Lấy DS chi tiết gọi món" as UC_detail
usecase "In hóa đơn" as UC_invoice
usecase "Tạo & lưu hóa đơn" as UC_save
usecase "Cộng điểm hội viên" as UC_point
usecase "Áp dụng ưu đãi / Voucher" as UC_voucher

UC08 .> UC_calc : <<include>>
UC08 .> UC_order : <<include>>
UC08 .> UC_invoice : <<include>>
UC08 .> UC_point : <<include>>
UC_calc .> UC_time : <<include>>
UC_order .> UC_detail : <<include>>
UC_invoice .> UC_save : <<include>>
UC_voucher .> UC08 : <<extend>>
}

Receptionist --> UC08
@enduml