@startuml

left to right direction
skinparam packageStyle rectangle
actor "Chủ DN (Admin)" as Admin

package "Hệ thống Quản lý Karaoke" {
usecase "QL Tài khoản NV" as UC21
usecase "Đăng nhập" as UC01
usecase "Xem DS tài khoản" as UC_view
usecase "Tạo tài khoản mới
& gán phân quyền" as UC_create
usecase "Khóa / Mở tài khoản NV" as UC_lock
usecase "Reset mật khẩu" as UC_reset

UC21 .> UC01 : <<include>>
UC21 .> UC_view : <<include>>
UC_create .> UC21 : <<extend>>
UC_lock .> UC21 : <<extend>>
UC_reset .> UC21 : <<extend>>
}

Admin --> UC21
@enduml