@startuml

left to right direction
skinparam packageStyle rectangle
actor "NV Lễ tân" as Receptionist

package "Hệ thống Quản lý Karaoke" {
usecase "Kiểm kê hàng tại quầy" as UC09
usecase "Đếm số lượng thực tế" as UC_count
usecase "Tạo phiếu kiểm kê" as UC_note
usecase "Báo cáo chênh lệch" as UC_report

UC09 .> UC_count : <<include>>
UC09 .> UC_note : <<include>>
UC_report .> UC09 : <<extend>>
}

Receptionist --> UC09
@enduml