@startuml

left to right direction
skinparam packageStyle rectangle
actor "Chủ DN (Admin)" as Admin

package "Hệ thống Quản lý Karaoke" {
usecase "QL Danh mục chung" as UC17
usecase "Đăng nhập" as UC01
usecase "Tìm kiếm danh mục" as UC_search
usecase "Thiết lập menu F\&B" as UC_menu
usecase "Thiết lập bảng giá phòng" as UC_price
usecase "Thiết lập khuyến mãi" as UC_promo
usecase "Thêm danh mục mới" as UC_add
usecase "Cập nhật / Xóa danh mục" as UC_update

UC17 .> UC01 : <<include>>
UC17 .> UC_search : <<include>>
UC_menu .> UC17 : <<include>>
UC_price .> UC17 : <<include>>
UC_promo .> UC17 : <<include>>
UC_add .> UC17 : <<extend>>
UC_update .> UC17 : <<extend>>
}

Admin --> UC17
@enduml