@startuml

left to right direction
skinparam packageStyle rectangle
actor "Chủ DN (Admin)" as Admin

package "Hệ thống Quản lý Karaoke" {
usecase "QL KH toàn hệ thống" as UC18
usecase "Đăng nhập" as UC01
usecase "Tìm kiếm KH (tên/SĐT)" as UC_search
usecase "Xem lịch sử sử dụng" as UC_history
usecase "Xem điểm tích lũy & hạng" as UC_points
usecase "Khóa tài khoản KH" as UC_lock

UC18 .> UC01 : <<include>>
UC18 .> UC_search : <<include>>
UC_history .> UC18 : <<include>>
UC_points .> UC18 : <<include>>
UC_lock .> UC18 : <<extend>>
}

Admin --> UC18
@enduml