@startuml

left to right direction
skinparam packageStyle rectangle
actor "QL Chi nhánh" as Manager

package "Hệ thống Quản lý Karaoke" {
usecase "Quản lý kho" as UC13
usecase "Theo dõi tồn kho" as UC_track
usecase "Duyệt phiếu nhập hàng" as UC_approve
usecase "Nhập hàng" as UC_import
usecase "Đếm & nghiệm thu" as UC_count
usecase "Tạo phiếu nhập" as UC_receipt
usecase "Hủy hàng" as UC_cancel
usecase "Tạo phiếu hủy" as UC_creceipt
usecase "Gửi đơn mua hàng" as UC_order

UC13 .> UC_track : <<include>>
UC_approve .> UC_track : <<include>>
UC_import .> UC13 : <<extend>>
UC_cancel .> UC13 : <<extend>>
UC_order .> UC_track : <<extend>>
UC_import .> UC_count : <<include>>
UC_import .> UC_receipt : <<include>>
UC_cancel .> UC_creceipt : <<include>>
}

Manager --> UC13
@enduml