@startuml

left to right direction
skinparam packageStyle rectangle
actor "Chủ DN (Admin)" as Admin

package "Hệ thống Quản lý Karaoke" {
usecase "QL Hệ thống CN" as UC16
usecase "Đăng nhập" as UC01
usecase "Xem DS chi nhánh" as UC_view
usecase "Thêm chi nhánh mới" as UC_add
usecase "Cập nhật / Xóa CN" as UC_update

UC16 .> UC01 : <<include>>
UC16 .> UC_view : <<include>>
UC_add .> UC16 : <<extend>>
UC_update .> UC16 : <<extend>>
}

Admin --> UC16
@enduml